version: "3"

services:
  monolithic:
    build: ./monolithic

  authors:
    build: ./microservices/authors-service
    volumes:
      - ./microservices/authors-service:/app

  books:
    build: ./microservices/books-service
    volumes:
      - ./microservices/books-service:/app

  countries:
    build: ./microservices/countries-service
    volumes:
      - ./microservices/countries-service:/app
  
  languages:
    build: ./microservices/languages-service
    volumes:
      - ./microservices/languages-service:/app

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - monolithic
      - authors
      - books
      - countries
